### ISSUE TITLE
Error when running set proofing language

### ISSUE THREAD

**Issue by richooms** [iappyx/Instrumenta#12]
**Describe the bug**
Using the set proofing language to UK English on all objects and all slides brings up an error on Mac
<img width="371" alt="image" src="https://user-images.githubusercontent.com/3234392/128747252-6561487c-5be3-4541-adf1-7fcd76f9212e.png">

**To Reproduce**
1. Go to 'the instruments tab in powerpoint'
2. Click on 'Set proofing language for all objects and slides'
3. Select 'English UK '
4. Press ok
5. See error as depicted in image above

**Expected behavior**
All objects should have a new proofing language

**Desktop (please complete the following information):**
 - OS: apple OSX
- Powerpoint version office 365

**Comment by iappyx** [comment]
Hi richooms, I'll try to reproduce the issue. I know this was an issue in previous versions of the plugin. Are you using the latest version (v1.0)?

**Comment by richooms** [comment]
I was using an old version. My bad!
