### ISSUE TITLE
False positive Windows Security reports for Instrumenta

### ISSUE THREAD

**Issue by Chouffy** [iappyx/Instrumenta#14]
**Describe the bug**
When launching PowerPoint, Windows Security block the load of Instrumenta due to a detected "Trojan".
PowerPoint throw an error "Sorry, for some reason PowerPoint couldn't load the InstrumentaPowerpointToolbar add-in.".

**To Reproduce**
1. Have Instrumenta as a PowerPoint Add-Ins
2. Start PowerPoint

**Expected behavior**
No error, Instrumenta loads like yesterday (14 October 2021).

**Screenshots**
PowerPoint:
![image](https://user-images.githubusercontent.com/9288966/137456273-bb02a638-2845-4c51-8fed-1c87de1e512a.png)

Windows Security:
![image](https://user-images.githubusercontent.com/9288966/137456238-488c5222-ceb3-49c9-810f-373877aeeb08.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2 build 19042.1237
 - Instrumenta v1.0
 - Windows Security informations
 - > Security intelligence version 1.351.453.0
 - > Version created on 2021-10-15 04:20
 - > Last update on 2021-10-15 08:52 CET

**Comment by iappyx** [comment]
Thanks! Not sure why this false positive was given. Happy that it has been corrected.

**Comment by iappyx** [comment]
Got another report today by someone who had the same message. Could be outdated defintions of Windows Defender. Anyone also experiences this issue?

**Comment by iappyx** [comment]
Both release and beta report as clean:

[https://www.virustotal.com/gui/url/745bf4e96def479c51d8e00c815ff32a23ec66371d27f6fd8b2dcb61319a4723?nocache=1](https://www.virustotal.com/gui/url/745bf4e96def479c51d8e00c815ff32a23ec66371d27f6fd8b2dcb61319a4723?nocache=1)
[https://www.virustotal.com/gui/url/81bd4c98848061d5eb8838e7667c38329730bc1e38ebed387defc5fbf3f72d48?nocache=1](https://www.virustotal.com/gui/url/81bd4c98848061d5eb8838e7667c38329730bc1e38ebed387defc5fbf3f72d48?nocache=1)

**Comment by iappyx** [comment]
I just submitted the sample to Microsoft just like Chouffy did before. Keep you posted.

**Comment by Chouffy** [comment]
I did a manual update and then scan of the addon, nothing comes up.
My security intelligence version is `1.252.2267.0`

**Comment by iappyx** [comment]
instrumentapowerpointtoolbar.pptm

Submission ID: xx

Status: Completed

Submitted by: xx

Submitted: Dec 7, 2021 21:30:42

User Opinion: Incorrect detection

Analyst comments:


                At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
     3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus

**Comment by iappyx** [comment]
instrumentapowerpointtoolbar.ppam

Submission ID: xx

Status: Completed

Submitted by: xx

Submitted: Dec 7, 2021 21:16:41

User Opinion: Incorrect detection

Analyst comments:


                At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
     3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus

**Comment by iappyx** [comment]
Another false positive. Closing this issue.

**Comment by iappyx** [comment]
Now the new version is also reported as Script/Sabsik.TE.A!ml and Script/Wacatac.B!ml. 

Again submitted the sample to Microsoft. Let's wait and see what comes out of it.

**Comment by iappyx** [comment]
instrumentapowerpointtoolbar.ppam

Submission ID: xx

Status: In progress

Submitted by: xx

Submitted: Dec 8, 2021 10:53:17

User Opinion: Incorrect detection

Analyst comments:


                At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
     3. Run "MpCmdRun.exe -SignatureUpdate"

**Comment by iappyx** [comment]
False positive seems to be solved with security intelligence version: 1.353.2287.0

Keeping this open in case any new reports.

**Comment by Chouffy** [comment]
@iappyx it's funny because Microsoft's message is a bit different from the first time:
* `We have removed the detection.  ...` -> suggesting they did something at the beginning
* `  At this time, the submitted files do not meet our criteria ...` -> suggesting that they did nothing 

Where did you get those reports? from users or yourself?

**Comment by iappyx** [comment]
I got one report from someone I know. And then I also experienced it on my private development machine and on my work laptop. Windows Defender actually deleted some of my beta versions, had to revert to a backup, nothing lost ;-)

> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed.

Unclear messages indeed. They still say they have removed the detection, but they keep it open that they could flag it again in the future?

I've also sent them an e-mail asking what piece of the code triggers this false positive.

**Comment by iappyx** [comment]
No more false positive detections found. Closing this for now.

**Comment by sancarn** [comment]
@iappyx I'm getting the same with some Excel macro software I've made: https://github.com/sancarn/stdVBA/issues/75

Wondering where you report these false positives to? Is there a link to submit false positives to microsoft?

**Comment by Chouffy** [comment]
> @iappyx I'm getting the same with some Excel macro software I've made: [sancarn/stdVBA#75](https://github.com/sancarn/stdVBA/issues/75)
> 
> Wondering where you report these false positives to? Is there a link to submit false positives to microsoft?

Yes - please check post 3 in this thread :)

**Comment by iappyx** [comment]
Indeed that's the one. Have used this for every major release since.
