### ISSUE TITLE
Autofit options for Text Box

### ISSUE THREAD

**Issue by Chouffy** [iappyx/Instrumenta#15]
**Is your feature request related to a problem? Please describe.**
I would like to have an icon in Instrumenta to choose the Autofit for the selected shape(s) in order to save time.

**Describe the solution you'd like**
This is how to access it manually:
1. Right-click on a Shape
2. Click _Format Shape_
3. Go to _Size & Properties_ tab (usually the 3rd option)
4. Expand the _Text Box_ section
5. Select either
    * _Do not Autofit_
    * _Shrink text on overflow_
    * _Resize shape to fit text_

An elegant solution would be to have an icon in Instrumenta in the Text section, with the ability to select the 3 options mentioned in step 5.

**Describe alternatives you've considered**
Manual selection, which is a bit not nice

**Additional context**
![image](https://user-images.githubusercontent.com/9288966/145057261-f1b489fc-2e7b-469e-b41e-50242ef8f4ee.png)

**Comment by iappyx** [comment]
Good idea! I would also use that, and today it's quite hidden in PPT. Will look into it.

**Comment by iappyx** [comment]
Features are now included in the latest beta (1.02): [https://github.com/iappyx/Instrumenta/raw/main/bin/InstrumentaPowerpointToolbar.ppam](https://github.com/iappyx/Instrumenta/raw/main/bin/InstrumentaPowerpointToolbar.ppam)

**Comment by Chouffy** [comment]
That works perfectly, thanks a lot @iappyx !
