### ISSUE TITLE
Some text-related functions aren't working when Text shapes are grouped

### ISSUE THREAD

**Issue by Chouffy** [iappyx/Instrumenta#16]
**Describe the bug**
Some text-related functions aren't working when Text shapes are grouped.
Affected functions are:
* Toggle Text Wrap
* Toggle autofit
* Remove text

**To Reproduce**
1. Create a Text box and add some long text inside
2. Click on Toggle Text Wrap
3. Change size of the shape
4. Confirm that it works as expected
5. Duplicate the shape
6. Make a group out of those 2 shapes
7. Try to use Toggle Text Wrap when selecting the group or when selecting a Text shape inside the group
8. Get the error "No text capable shape selected."

**Expected behavior**
Same behavior than when selecting the Text shape not in a group

**Screenshots**
![image](https://user-images.githubusercontent.com/9288966/151378008-33723dce-7e69-4c2a-8c75-866b1add00c7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - PowerPoint 2112 build 14729.20260 Click to run

**Comment by iappyx** [comment]
Hi Chouffy, that's right, the current code does not support this. 
Will look into it.

**Comment by iappyx** [comment]
Latest beta 1.03 now solves this for the three text functions you mentioned. Other functions could also still be improved in handling situations where shapes are grouped. Will close this issue, but other functions will be improved in next releases.

**Comment by iappyx** [comment]
Now also changed the behaviour for other text functions in version 1.04.
