### ISSUE TITLE
Table of Contents page

### ISSUE THREAD

**Issue by Vadigor** [iappyx/Instrumenta#20]
I routinely create a sort of "Table of Content" page with a basic SmartArt showing the topics. Usually that's 1:1 with the sections. I'll also add hyperlinks to each section usually. This is pretty basic but it all tends to take quite a bit of work to set-up, especially the hyperlinks.

The "Agenda page" already seems to do a sort of inventory of sections. If we could reuse that logic to create SmartArt with an entry for each (2nd+) section and hyperlink the shape to it, the rest of the formatting could be done with regular design tools.

(A way to add agenda pages to the second slide in each section instead of the first, which is often a chapter slide, would also be interesting. But perhaps that should be its own request. 😉)

**Comment by iappyx** [comment]
Hi @Vadigor, thanks for your suggestion. I also don't like the current agenda page set-up, and would like to change that in the future. Using "block" that can be linke to the different pages is something I would like to include. Not sure if SmartArt is the way to go, there are several types, and I found it is usually quite hard to code against smart art. Will look into agenda pages improvements.

**Comment by Vadigor** [comment]
The main advantage of SmartArt is the ability to edit contents and resize and apply styles at will, but of course there's a trade-off to consider if they're a pain to code.

I mainly use them since the decks I routinely build are around for a long time and get constant updates. Project status slides, solution design decks, templates etc. So I'd use a macro as an accelerator for the first set-up but might do later updates manually rather than recreating slides. Might be different from the way others approach it.

**Comment by iappyx** [comment]
Sorry, wontfix for now. Tried to code against SmartArt, but did not work well for me.
