### ISSUE TITLE
MS Defender reports "threats" when scanning the PPPAM

### ISSUE THREAD

**Issue by SteveRindsberg** [iappyx/Instrumenta#21]
Not a bug as such but the Vulnerability reporting option on GitHub simply returns me to the main Issues page.

I downloaded the PPAM today (19 June 2022) and scanned it with MS Defender (Win10/64-bit). This is the report, which I would assume is a false positive, but wanted to let you know about it in case others complain.

![image](https://user-images.githubusercontent.com/45697110/174491683-2ad2ef23-a355-4945-bbea-6eb5b4857719.png)

**Comment by iappyx** [comment]
Thanks for sharing. 

Unfortunately, Instrumenta has had several false positives in the past with MS defender. All were submitted to Microsoft and resolved. Also see #14. Will submit it again and report back here.

**Comment by iappyx** [comment]
No viruses found here: https://www.virustotal.com/gui/file/ad8f95bee4aa13a4c769afdc6d975fe8db22c6e54d35f5360a57f5a112a7e6e8?nocache=1

Now submitting to Microsoft.

**Comment by iappyx** [comment]
![Screenshot 2022-06-19 at 19-18-19 Submission details (b3af1406-1452-45b6-9a5c-68158c297639) - Microsoft Security Intelligence](https://user-images.githubusercontent.com/22550917/174492872-bbe91453-285b-49c7-a768-d7c9113adcf1.png)

No threats found. All 105 rows show "Not malware". Hope it is resolved at your end when you update your virus definitions. Thanks again!

**Comment by SteveRindsberg** [comment]
Thanks.

 

Someone on Reddit’s r/powerpoint subreddit was asking about whether Instrumenta was safe.

I tried it out, mentioned the Defender issue but also pointed out how notorious Defender is for barking at perfectly innocuous software.

Also mentioned that someone who was trying to slip malware onto folks’ computers was HIGHLY unlikely to release it with visible source code, as you’ve done.

 

VERY nice work, by the way.

**Comment by iappyx** [comment]
> Thanks. Someone on Reddit’s r/powerpoint subreddit was asking about whether Instrumenta was safe. I tried it out, mentioned the Defender issue but also pointed out how notorious Defender is for barking at perfectly innocuous software. Also mentioned that someone who was trying to slip malware onto folks’ computers was HIGHLY unlikely to release it with visible source code, as you’ve done. VERY nice work, by the way. >

Thank you. Coming from a PowerPoint legend that is a huge compliment!

Also thanks for providing a fair and balanced answer on Reddit. What you explained there is exactly what happened.

**Comment by SteveRindsberg** [comment]
Happy to help, especially having been in the same situation myself, along with a few other add-in writers.
