### ISSUE TITLE
It would be amazing if adding a button for "exporting selected page as ppt file"

### ISSUE THREAD

**Issue by houseffy** [iappyx/Instrumenta#24]
Hi Team!
I noticed that we only got several exporting options such as "export as pdf" or "email selected pages". It would be amazing if adding a button for "exporting selected page as ppt file".
TBH, that's the first function I was looking for when searching such ppt toolbox as you guys developed hhhh.
Overall it's still a great and convenient product for me! Thanks for all the developing team members :)

**Comment by iappyx** [comment]
Hi @houseffy, this should not be that difficult to implement. Will look into it. When I need it I usually use the e-mail function and then drag the file somewhere. But that workflow can be improved indeed!

**Comment by iappyx** [comment]
Working on it, will be part of next beta.

**Comment by iappyx** [comment]
This is now part of the latest beta 1.23!
