### ISSUE TITLE
Instrumenta cannot be loaded after Update

### ISSUE THREAD

**Issue by TobiasBenz** [iappyx/Instrumenta#25]
**Describe the bug**
After the most recent office 365 update Instrumenta cannot be loaded any more. I just get the error message:

"PowerPoint couldn't load the add-in ".../InstrumentaPowerpointToolbar.pam"

**To Reproduce**
Always happens when opening PowerPoint

**Desktop (please complete the following information):**
 - OS: MacOS 12.5.1
 - PowerPoint Version 16.64 (22081401)

**Comment by iappyx** [comment]
Hi! Are you using the latest version of Instrumenta, and what happens when you uninstall (delete) and reinstall the plugin?

**Comment by iappyx** [comment]
Hi @TobiasBenz I've checked on my Mac. I have the same PPT version and Instrumenta 1.21 does not throw an error here. Did you manage to resolve it by using the steps mentioned above?

**Comment by TobiasBenz** [comment]
Hey @iappyx ,

sorry for the late reply, I did not get the notification. 

the issue is resolved. From what I undesrtand after the update PowerPoint required macro permission for intrumenta again. Delting only the pam file does not resolve the issue. I needed to remove the instrumenta from add ins and add it again. 

Thanks for your quick help :)
