### ISSUE TITLE
Allow subsections on Agenda pages

### ISSUE THREAD

**Issue by fmms** [iappyx/Instrumenta#26]
**Is your feature request related to a problem? Please describe.**
I am very thankful that you plugin has the agenda option. Thanks for that.

However, right now all agenda items are on one level. In general I would like to have an agenda like

* topic 1
  * topic 1.1
  * topic 1.2
* topic 2

**Describe the solution you'd like**
I believe most likely you have chosen the approach to use sections instead of a wizard dialog as a foundation for a good reason.
Maybe it would be solved with a minimal addition that ione could add a specific number of stars in the section name and they would be indentet accordingly?

**Describe alternatives you've considered**

**Additional context**
I am using version 1.21

**Comment by iappyx** [comment]
Hi @fmms, good idea. The sections are used for a reason indeed, but I think its possible to add the stars in the section name as you suggest. Will have a look.

**Comment by iappyx** [comment]
Forgot to mention it in the notes, but this functionality was added to the latest beta v1.25
