### ISSUE TITLE
Show "Enable Macro" button when adding the add-in in Power Point.

### ISSUE THREAD

**Issue by bfkf** [iappyx/Instrumenta#27]
**Describe the bug**
If a user have never enabled a third-party add-in in PowerPoint, the "Enable Macro" button when adding the add-in will not show up. It is necessary to change its settings in the add-in's properties the first time to have it show up.
**To Reproduce**
1. Right-click on the Instrumenta file and choose Properties from the context menu.
2. At the bottom of the General tab, select the Unblock checkbox and select OK.

**Expected behavior**
When adding the add-in the security error will show up and the "Enable Macro" button will also show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/76712307/192515786-3dc3b033-2d3c-40a6-a3ad-7cbdcfb72250.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 22

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20+
 - OS: Android 11
 - Browser Chrome
 - Version 22

**Additional context**
None.

**Comment by iappyx** [comment]
Hi @bfkf, thanks for bringing this to my attention. I don't recognize this behavior on my development machines, I'll try to reproduce. As far as I can remember, when I installed it on other PCs I always got the enable macros message.

Not sure if I can fix this, as it seems to be a built-in feature in Windows.

**Comment by Vadigor** [comment]
Not sure why there's a screenshot for a Word doc here, but I _can_ reproduce this on a personal Office 365 and Windows 10. Downloaded .ppam is blocked by default, giving an error when opening it.

![image](https://user-images.githubusercontent.com/38330302/192642010-308cf627-3c23-4dde-949f-37ef8f0e176c.png)

![image](https://user-images.githubusercontent.com/38330302/192641962-90c178fe-7ac3-4cfd-ac18-fec0eaab2503.png)

**Comment by iappyx** [comment]
Thanks @Vadigor! Will update the installation instructions with the info and links you provided.

**Comment by iappyx** [comment]
Updated in documentation.
