### ISSUE TITLE
Split text into multiple objects with the formatting intact

### ISSUE THREAD

**Issue by hairlessmonkey** [iappyx/Instrumenta#29]
@iappyx  If this is achieved, it will split the text from one shape/textbox into multiple shapes by paragraph with all the formatting intact with respect to the original textbox.

Would be great if the reverse of the above can be done too, i.e., multiple text boxes club together in one textbox.

**Comment by iappyx** [comment]
Good one, will have a look

**Comment by hairlessmonkey** [comment]
Thanks a a lot and by the way Happy New Year.

Looking forward for an update.

**Comment by iappyx** [comment]
This functionality was added to the latest beta v1.22. Does not properly work on Mac yet.

**Comment by iappyx** [comment]
Improved behavior in latest beta 1.23, now also works on Mac!
