### ISSUE TITLE
Paste and insert - Emoji doesn't work

### ISSUE THREAD

**Issue by Auranticus** [iappyx/Instrumenta#33]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by iappyx** [comment]
What OS are you using? For me it did not work in Windows 10 anymore, but in Windows 11 it did. Will look into it.

**Comment by Auranticus** [comment]
Hi, I am using win10. 
Thanks!
     Am Mittwoch, 8. März 2023, 22:25:50 MEZ hat iappyx ***@***.***> Folgendes geschrieben:  
 
 


What OS are you using? For me it did not work in Windows 10 anymore, but in Windows 11 it did. Will look into it.

**Comment by iappyx** [comment]
Hi I can confirm it also does not work at another Win10 device I use. Do not have a solution yet. Will keep you posted.

**Comment by ace9790** [comment]
I am not sure if I was trying it incorrectly before, or if you fixed this in the new beta. 
It does work for me now, though in a different way then expected. 

I thought this would add SVG pictograms. However, it actually enters smileys as text, i.e., you need to be in "typing mode" within a shape. Then it works.

**Comment by iappyx** [comment]
This is indeed intended behavior. It does not add SVG pictograms, it enters smileys as text, for which it uses the built in functionality of Windows and Mac OS.

**Comment by Auranticus** [comment]
thank you! now I understand and it works.
Best regards!
     Am Montag, 17. Juni 2024 um 11:13:10 MESZ hat ace9790 ***@***.***> Folgendes geschrieben:  
 
 


I am not sure if I was trying it incorrectly before, or if you fixed this in the new beta.
It does work for me now, though in a different way then expected.

I thought this would add SVG pictograms. However, it actually enters smileys as text, i.e., you need to be in "typing mode" within a shape. Then it works.
