### ISSUE TITLE
Mail merge: Run-time error '13' Type Mismatch

### ISSUE THREAD

**Issue by mcgradem99** [iappyx/Instrumenta#36]
**Describe the bug**
When running mail merge (Manually replace merge all merge fields on all slides'), merge begins but then error box appears with message "Run-time error '13' Type Mismatch"

**To Reproduce**
1. Go to Advanced
2. Click on Insert Empty Merge Field (or Insert Merge Fields from Excel)
3. Manually replace all merge fields on all slides 

**Screenshots**
![image](https://github.com/iappyx/Instrumenta/assets/13208925/93ae937d-cf2c-49ed-b7c4-177ef549782e)

**Desktop (please complete the following information):**
Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎22/‎03/‎2022
OS build	19044.2965
Experience	Windows Feature Experience Pack 1000.19041.1000.0

PowerPoint Version 2202 (Build 14931.21000 Click-to-Run)

**Comment by iappyx** [comment]
Can you provide an anonymized example of the excel that you use?

**Comment by mcgradem99** [comment]
I stand corrected - it actually works fine if you use an Excel. It's the 'Manually replace merge all merge fields on all slides' option which produces the error (see images for example). Thank you :) 

![image](https://github.com/iappyx/Instrumenta/assets/13208925/4361ac2b-3291-419e-a7f9-5fa42f14c670)
![image](https://github.com/iappyx/Instrumenta/assets/13208925/7cbe08af-54a7-4be5-9063-3935d3b89b39)
