### ISSUE TITLE
Shortcut 

### ISSUE THREAD

**Issue by Edoprem** [iappyx/Instrumenta#37]
Hi, first of all thank you for the excellent work you did, secondly I wanted to ask if it was possible to assign certain shortcuts to some commands to make use more fluid. Thank you so much

**Comment by ace9790** [comment]
You can do that yourself by using the quick access toolbar.

Right click on a function within instrumenta (or any other tab) and "add to quick access toolbar".

The symbol will appear above or below the toolbar, depending on your settings. You can change the order here if you want.

Then your shortcuts are ALT + 1, ALT + 2, etc., depending on the position of the symbol


![image](https://github.com/iappyx/Instrumenta/assets/152002958/e9a34d0c-ecc7-434d-abee-20926c3ea1bc)

**Comment by iappyx** [comment]
I have been working on a keyboard shortcut companion called [Instrumenta Keys](https://github.com/iappyx/Instrumenta-Keys). It only works on Windows and is highly experimental.

**Comment by SCHOUTER** [comment]
@iappyx I haven't looked into the code but a similar [project ](https://github.com/rodrigolourencofarinha/ProDeck)like yours does use custom shortcuts somehow. I can press alt+x+[defined shortcut]. This would be SO much better!

<img width="466" height="191" alt="Image" src="https://github.com/user-attachments/assets/218600f3-a598-4ff0-9412-c535d19fbc09" />

<img width="1594" height="130" alt="Image" src="https://github.com/user-attachments/assets/d3ac647e-e9c8-45d4-abfc-1952e267c473" />
