### ISSUE TITLE
Inability to Customize Instrumenta Tabs and Commands in PowerPoint for macOS

### ISSUE THREAD

**Issue by mueezkq** [iappyx/Instrumenta#39]
**Describe the bug**
After installing the Instrumenta PowerPoint add-in on macOS, I'm unable to modify Instrumenta tabs and commands within the PowerPoint ribbon and toolbar. While modifications to existing default PowerPoint tabs and commands are still possible, any attempts to customize or add Instrumenta-specific commands fail. This issue is specific to macOS, as the functionality operates without issues on Windows 11. The problem has been ongoing since October 2023, and updates to PowerPoint and Instrumenta have not resolved it.

**To Reproduce**

1. Install Instrumenta PowerPoint add-in on a macOS system.
2. Open PowerPoint and try to modify or add to the Instrumenta tab or commands.
3. Attempt to customize default PowerPoint tabs and commands for comparison.
4. Notice that while default PowerPoint tabs and commands can be modified, any changes to Instrumenta tabs and commands cannot be made.

**Expected behavior**
Users are expected to be able to customize both default PowerPoint and Instrumenta-specific tabs and commands on macOS, similar to the functionality on Windows. This includes adding new commands, modifying existing ones, and creating customizations without restrictions.

**Desktop (please complete the following information):**

1. OS: macOS Sonoma 14.4
2. Browser: Safari
3. PowerPoint Version: Version 16.83 (24031120) 
4. Instrumenta Version: Instrumenta 1.30

**Additional context**
This limitation on customizing the Instrumenta ribbon and toolbar in PowerPoint for Mac has persisted since October 2023, despite updates to both PowerPoint and Instrumenta. The ability to modify default PowerPoint commands and tabs remains unaffected. This specific issue with Instrumenta customizations contrasts with its fully functional capability on Windows, impacting the usability and customization potential of Instrumenta on macOS.

**Comment by iappyx** [comment]
Hi @mueezkq, I am afraid this is a limitation of PowerPoint for Mac that does not allow you to customize custom ribbons like Instrumenta. The only thing you can do is switch from "Pro-mode" to "Review mode" in Instrumenta settings or you can include Instrumenta commands in the Quick Access Bar.
