### ISSUE TITLE
Transparency option

### ISSUE THREAD

**Issue by ace9790** [iappyx/Instrumenta#40]
Hi iappyx, 

love the toolbar, it is definately more user friendly than the two strategy consulting companies I worked for - amazing job!

The only function I am missing is a "set transparency" option for **shapes**. The ideal solution here would be a button which increases transparency by 20% in my opinion, and then goes from 100% to 0% again on the sixth press.

I wanted to add it to my own quick access toolbar, but somehow I am too stupid to find it...

**Comment by iappyx** [comment]
Hi @ace9790, nice one. Should be possible, will look into it.

**Comment by iappyx** [comment]
Included basic functionality in the latest beta!
