### ISSUE TITLE
QR Code API defunct

### ISSUE THREAD

**Issue by pascal-mw** [iappyx/Instrumenta#41]
**Describe the bug**
QR Code can’t be inserted since google API throws a 404 Error

**To Reproduce**
1. Go to ‚insert‘
2. Click on 'Insert QR'

**Expected behavior**
QR Code of given text should appear

**Solution**
src/Modules/ModuleQRCodes.bas

Needs update with a new API

proposed solution:

https://github.com/pascal-mw/Instrumenta/blob/9a8f1a2508d5eb374bb050a9d4dc25bdeffe37be/src/Modules/ModuleQRCodes.bas

would have created a pull request but those are not for non-contributors.

cheers!

**Comment by iappyx** [comment]
Thanks! Will update this as well.

**Comment by iappyx** [comment]
Fixed in latest beta.
