### ISSUE TITLE
Overruling default PowerPoint Alignment behavior

### ISSUE THREAD

**Issue by pascal-mw** [iappyx/Instrumenta#42]
**Is your feature request related to a problem? Please describe.**
Known from many other commercial Consulting PowerPoint Toolbars the default behavior when aligning objects (always aligns to object with most extreme position) is overridden and instead alignment happens to last selected (or first selected) object. Which lets you snap objects much quicker into place and tidy up a slide.

**Describe the solution you'd like**
- Ideally a setting where I can choose from default behavior, last selected or first selected 
- Alignment buttons in instruments perform the trick
- See a mergeable fork I discovered here: https://github.com/nicofilliol/Instrumenta

**Describe alternatives you've considered**
Alternatively no custom setting, this would help keep codebase slim. Default behavior via PowerPoint buttons,
Last selected via instrumenta buttons (easy fix, merged fork)

Would love feedback!
Amazing project! Thank you so so much for it!
Cheers!

**Comment by iappyx** [comment]
Hi @pascal-mw, this is indeed very useful. Will update it in the next version of Instrumenta.

**Comment by iappyx** [comment]
Added to latest beta. See Instrumenta settings.
