### ISSUE TITLE
Thanks for the new beta. 3 more suggestions :)

### ISSUE THREAD

**Issue by ace9790** [iappyx/Instrumenta#44]
Hi!

1. Thanks for implementing the transparency option! It works great, but I suggest to increase the steps, i.e., 20%, 40%, 60%, ...; the 10% currently require a lot of clicking :)

2. A toggle next to "wrap text" to change how shapes change with text: adjust to fit text, keep constant, ...)

3. In addition to increasing the line spacing, it would be great to add 2 new buttons: "**In**crease line spacing before AND after paragraph [prob. by 3 points each, i.e., 6 in total ]" and **DE**crease line spacing before AND after paragraph. Allows to make multiple bullets more readable while keeping it in the the middle

Thanks again!!

**Comment by iappyx** [comment]
1) will update in next version
2) I think you mean toggle autofit? This feature is already supported. See in "Text"  the first section, top right button.
3) can look into it

**Comment by iappyx** [comment]
Implemented 1 and 3 in the latest beta.

**Comment by ace9790** [comment]
You are a rockstar! I sent over some more coffees ;)
