### ISSUE TITLE
3 more suggestions

### ISSUE THREAD

**Issue by ace9790** [iappyx/Instrumenta#45]
I repeat myself: I love Instrumenta & am definately a power user. 

I know I keep spamming suggestions, I hope it does not get too annoying :)

1. Distributing elements horizontally or vertically works well. When **selecting only 1 shape** and using the normal powerpoint function to distribute horizontally or vertially, it will align the shape in the middle of the slide. With the function on Instrumenta this does not work currently

2. Often people update a slide but keep the original. When finalizing it, it would be great to have a button which hides the slide and then sends it to the back: it is out of sight in presentation mode, does not irritate when working on the doc, but is still there :) 

3. Under the special characters button you currently have Euro, Copysign, etc. It would be great to have a protected space there as well (Character Code 00A0 from Hex)

**Comment by iappyx** [comment]
Hi @ace9790 ! No worries, not annoying at all. Happy to improve the tool.

1) this should also be the default behaviour in Instrumenta. Not sure why it does not work for you. Windows or Mac?

2 and 3 I can look into

**Comment by ace9790** [comment]
I am on a windows (work computer, many functionalities are limited due to security concerns).

**Comment by ace9790** [comment]
By the way, this is the error I get

![image](https://github.com/iappyx/Instrumenta/assets/152002958/9ee97e02-a181-4c1c-a581-ce098f3956fc)

**Comment by iappyx** [comment]
Sorry I thought you meant clicking align center (6 buttons to the left). That does work in that way.

Can also build this into the distribute horizontally/vertically functions of Instrumenta

**Comment by iappyx** [comment]
Latest beta now includes these three features!
You can find 2 in the cleanup menu. It processes all selected slides.

**Comment by ace9790** [comment]
You are a ****************** Rockstar!!! Thanks!!!

**Comment by ace9790** [comment]
one minor improvement for the implemented "move to end and hide slide" feature: ideally at the end of the script, it would select the next slide (and thus shift the screen back).

Currently, the screen ends up at the end of the presentation, and then you need to scroll back to the position you started in.
Do you know what i mean?
