### ISSUE TITLE
F4 does not replicate actions

### ISSUE THREAD

**Issue by ace9790** [iappyx/Instrumenta#46]
Normally, pressing F4 should repeat the last action. 
It could be copying a text box, changing the format of shapes, distributing elements, etc. 

Somehow it does not work when using any of the functions in Instrumenta. 

Definitely not an urgent bug, but I thought I might as well report it :)

**Comment by iappyx** [comment]
Did not know that shortcut, in my Win11 F4 does nothing, also not for the built in controls.

**Comment by ace9790** [comment]
Hmm, weird. 

I thought this is the standard binding - apparently it is also the same for Ctrl + y. However, this also seems to not work with instrumenta. 

I wanted to fix it myself and found the guide linked below. However, There is no customization option in my PPT (365 enterprise), which I guess could be done from our IT side. I it is easiest if we just forget this topic ;D

https://support.microsoft.com/en-us/office/customize-keyboard-shortcuts-9a92343e-a781-4d5a-92f1-0f32e3ba5b4d
