### ISSUE TITLE
Shortcuts like McKinsey

### ISSUE THREAD

**Issue by ivandashchenko** [iappyx/Instrumenta#53]
I would like to propose adding keyboard shortcuts as in McKinsey plugin:
CTRL + ALT + LEFT for alignment to leftmost point of first object
CTRL + ALT + RIGHT for alignment to rightmost point of first object
CTRL + ALT + UP for alignment to top of first object selected
CTRL + ALT + DOWN for alignment to bottom of first object selected
SHIFT + ALT + V for distributing vertically
CTRL + SHIFT + V for distributing horizontally
ALT + Q for new textbox
CTRL + 0 for new sticker

**Comment by iappyx** [comment]
Hi, would love to do that, but with the current code/method this is unfortunately not possible. See: [https://github.com/iappyx/Instrumenta/issues/37](https://github.com/iappyx/Instrumenta/issues/37)
