### ISSUE TITLE
Add steps counter

### ISSUE THREAD

**Issue by davidemora** [iappyx/Instrumenta#6]
why not having a new feature that adds a steps counter on the slide?
By steps counter I mean a small circle with a number inside: for each new one you add the number get increased.

See the attached picture, maybe it's clearer.

Ideally it should be possible to have settings like:
- start a new steps list for each slide or per presentation
- background shape settings
- font choice

Example
![firefox_7q3ppFS8pD](https://user-images.githubusercontent.com/876327/116420851-a5523900-a83e-11eb-93ae-46459a0a785f.png)

Steps
1. add the title
2. add the description
3. click submit

**Comment by iappyx** [comment]
Thanks @davidemora this is already on the backlog. Did not yet think of background shape settings and font choice. Will pick it up!

**Comment by iappyx** [comment]
I've released a new version with step counter functionality. It has been implemented as follows:

- You can add a step counter to a slide in the "Paste and insert" section (use the button with the "1"-icon)
- It will add the first step counter (1) in the right corner of the slide. 
- You can drag it anywhere, change color, dimensions and shape like you would do with any other shape. You should not change the text "1" though.
- If you add another step counter (2) it will add the next step counter with number "2" and it will copy the formatting, shape and dimensions of the previous step counter (1). In fact it will copy the formatting, shape and dimensions from the step counter with the highest number on the slide.

In the split-menu of this step counter button you will also have the option to add cross-slide step counters. These work in a similar way but will continue numbering from previous slides.

In the split-menu you will also find two options to easily select all step counters on the slide (e.g. for deleting or formatting the shapes quickly).

If you copy step counter shapes (e.g. to make a legend) it will still work as expected. 

I believe this way of implementing provides a lot of flexibility, without bothering the user to much with all kinds of screens / forms. Please let me know if this works for your use case as well.

**Comment by davidemora** [comment]
Works like a charm!
